services:
  claude-code-router:
    build: .
    container_name: claude-code-router
    ports:
      - "3456:3456"
      - "3457:3457"
    volumes:
      - ~/.claude-code-router:/root/.claude-code-router
    environment:
      - NODE_ENV=production
      # Override HOST setting to bind to all interfaces for Docker access
      - OVERRIDE_HOST=0.0.0.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3456/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
